### ISSUE TITLE
Nooo not another Bluetooth call bug!! Anything but that!

### ISSUE THREAD

**Issue by Trevelopment** [gartnera/headunit#105]
Hey @lmagder what you did with the audio focus is great work but I think from a comment in callbacks.cpp that you were anticipating this issue:
`else if (request.focus_type() == HU::AudioFocusRequest::AUDIO_FOCUS_GAIN_TRANSIENT) {
            audioMgrClient->audioMgrRequestAudioFocus(AudioManagerClient::FocusType::TRANSIENT); //assume navigation }`
That right there is not a great assumption to make because BTHF makes a request to gain transient audio focus as well.
So when a phone call comes in the AA stream takes audio focus first then gives it to BTHF but this causes the audio to stop playing and when the call is over audio does not start playing again.  The one exception to this is when you are in the entertainment context when you start up AA and playing external audio and have not switched to AA audio at all (that way AA does not try to take focus at the end of the call and the context change from phone to entertainment happens in the background).  
This is what the log entries look like when making a call (playing USB audio)
```
W: /home/mazda/headunit/hu/hu_aap.cpp:622: hu_handle_AudioFocusRequest : AudioFocusRequest Focus Request AA_CH_CTR: 2
audioMgrRequestAudioFocus(2)
requestAudioFocus({"sessionId":23})
{}
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"USB","streamModeName":"USB","newFocus":"lost","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 13 for stream USB
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","streamModeName":"MLENT","newFocus":"gained","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 23 for stream MLENT
AudioFocusHappend(2)
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","streamModeName":"MLENT","newFocus":"temporarilyLost","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 23 for stream MLENT
AudioFocusHappend(0)
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"BTHF","streamModeName":"BTHF","newFocus":"gained","destination":"Cabin","focusType":"transient","streamType":"Telephony"}
Found audio sessionId 15 for stream BTHF
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"BTHF","streamModeName":"BTHF","newFocus":"lost","destination":"Cabin","focusType":"transient","streamType":"Telephony"}
Found audio sessionId 15 for stream BTHF
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","streamModeName":"MLENT","newFocus":"gained","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 23 for stream MLENT
```
I tried to use the Notify signal handler and another flag variable when BTHF is the stream taking focus to stop the first audio focus change but by the time that signal hits it's already too late.  I will try some more things I have just been swamped because my company is running a prop auction for the show [Parks and Recreation](https://www.screenbid.com?headunit).

**Comment by lmagder** [comment]
Haha goddamit there was bound to be more. Something is wrong here, but I'm not sure what. The distinction between AudioManagerClient::FocusType::TRANSIENT and AudioManagerClient::FocusType::PERMANENT is really only used to control if the next/prev track buttons are passed on or not, so I'm not sure it's the problem.

Maybe what's going on here is that we are spontaneously given focus by the OS back to MLENT but we aren't telling AA due to the logic in AudioManagerClient::Notify() since it gets the event, but since pendingFocus was not set it never calls callbacks.AudioFocusHappend(currentFocus); 

Really the requestPending and pendingFocus variables are a hack since we can't pass the focus type into the request to know if AA wanted permanent or transient focus. Ideally we get that info from the payload in Notify() instead of stashing it inside AudioManagerClient since I think this breaking focus changes which don't originate from audioMgrRequestAudioFocus()/audioMgrReleaseAudioFocus() since the internal state is not updated correctly.

I notice the payloads in your log have "focusType":"transient" and "focusType":"permanent" in then, so we can get this data without the hack, but can we control that when we call requestAudioFocus (maybe adding more than sessionId?) so that when we get the gained notification for MLENT it will have the right JSON value for focusType corresponding to what was passed to AudioManagerClient::audioMgrRequestAudioFocus()?

You did a lot of digging to find the MLENT, did you find out what the full interface for requestAudioFocus is? would putting a focusType member into args for the requestAudioFocus call work?

**Comment by Trevelopment** [comment]
Yes!! we can pass the requestType too 
`requestAudioFocus(const int32_t& sessionId, const int32_t& requestType)`

**Comment by Trevelopment** [comment]
hey but are you sure that this isn't telling AA (on the MLENT stream) to take audio focus whenever the request is transient?
```
if (request.focus_type() == HU::AudioFocusRequest::AUDIO_FOCUS_RELEASE) {
    audioMgrClient->audioMgrReleaseAudioFocus();
} else if (request.focus_type() == HU::AudioFocusRequest::AUDIO_FOCUS_GAIN_TRANSIENT) {
    audioMgrClient->audioMgrRequestAudioFocus(AudioManagerClient::FocusType::TRANSIENT); //assume navigation
} else if (request.focus_type() == HU::AudioFocusRequest::AUDIO_FOCUS_GAIN || request.focus_type() == HU::AudioFocusRequest::AUDIO_FOCUS_UNKNOWN) {
    audioMgrClient->audioMgrRequestAudioFocus(AudioManagerClient::FocusType::PERMANENT); //assume media
}
```
because it looks to me like this method happen first when the request is made and audioMgrRequestAudioFocus will pretty much always get to the end when it is passed AudioManagerClient::FocusType::TRANSIENT is that right or am I seeing this wrong?

**Comment by Trevelopment** [comment]
Then that should work like you said if we pass (sessionId, requestType) MLENT, AudioManagerClient::FocusType::TRANSIENT to requestAudioFocus it won't try to take back the audio focus after the call or it will if it already had focus before that.

**Comment by Trevelopment** [comment]
@lmagder here are some things I figured out ( I could be wrong about or you may already know some of these things): 
- The audio channels within AA are like their own set of "streams" that are playing on the same stream (in the CMU) so registering MLENT puts all AA audio channels on that stream.
- Remember making that audio channel for Navigation? Well that's because there isn't one so navigation doesn't use the MLENT stream I think it just hops onto "default" and therefore does not need AA to request audio focus to hear it
- Now that we are using the MLENT stream that is registered as "permanent" there is no need to handle the FocusType per se. we should be keeping track of the focusState via newFocus in Notify() and using that variable to make audio focus decisions. And right now we really only care about GAIN, LOSS, & LOSS_TRANSIENT
- Transient streams automatically pass audioFocus back to the stream that has temporarilyLost focus when they themselves have lost focus so we don't need to handle that directly in the headunit code (for example if focus is taken by a bluetooth call the previous stream will be given back focus when it is finished)
- The 'Mic' audio channel is the only transient focus event within the AA stream  *but* since it is on the MLENT stream (which has focusType permanent) it is transient within the stream itself so we will need to manually switch to MLENT to hear it *or* try to register another transient audio stream and use it for the mic exclusively if that is even possible.   I think that making an automatic switch is unnecessary since the mic is always a button-triggered event it may be better to put something in the button press event.  Thats just a thought Im not totally sure the best way to handle this yet.

So from all that I have gotten closer to making all the transitions smooth but it's not perfect. This may help you think about it a little better and please if I am wrong about something correct me because it just makes it harder for me to figure things out when I'm wrong and don't know it.

**Comment by mishaaq** [comment]
> I think that making an automatic switch is unnecessary since the mic is always a button-triggered event it may be better to put something in the button press event.

@Trevelopment not only. Mic can be triggered by pushing knob to the right on Google Maps as far as I remember. This triggers voice search.

**Comment by Trevelopment** [comment]
@mishaaq youre right and actually if you press the mic on your phone it will trigger that event as well. In the PR Im about to post it fixes all the audio focus issues switching between phone calls and music inside or outside of AA. And the mic still works fine too not listening to music outside of AA like USB or radio then you can use the mic but you will still hear whatever you are listening to and have to switch audio back to AA to hear the responses.

**Comment by lmagder** [comment]
This is tough. Personally I would say that AA prompts not interrupting non-AA audio is a worse bug than this issue. (if I had to choose, hopefully not). I guess it depends what feature you prioritize. I drive with GMaps a lot listening to XM radio and almost never make phone calls :)

> •	The audio channels within AA are like their own set of "streams" that are playing on the same stream (in the CMU) so registering MLENT puts all AA audio channels on that stream.

Yeah, they are two different audio streams but we are playing them both back on the same "entertainmentMl" also device which is attached to MLENT by the CMU audio manager. This isn't required, like we could play them to differnt devices attached to different CMU streams if it helps somehow.

>•	Remember making that audio channel for Navigation? Well that's because there isn't one so navigation doesn't use the MLENT stream I think it just hops onto "default" (but I'm not totally sure because it is nowhere to be found in the logs) and therefore does not need AA to request audio focus to hear it

I don't think that's true. They both are played to entertainmentMl by our code so you need to switch to MLENT to hear either.

>•	Now that we are using the MLENT stream that is registered as "permanent" there is no need to handle the FocusType per se. we should be keeping track of the focusState via newFocus in Notify() and using that variable to make audio focus decisions. And right now we really only care about GAIN, LOSS, & LOSS_TRANSIENT

That's true but it would be better if we had a second stream other than MLENT which was not registered as permanent that we use when we only have transient AA focus so that the CMU audio manager would do the right thing.

>•	Transient streams automatically pass audioFocus back to the stream that has temporarilyLost focus when they themselves have lost focus so we don't need to handle that directly in the headunit code (for example if focus is taken by a bluetooth call the previous stream will be given back focus when it is finished)

Yeah, I think so. That's why it would be awesome to have the second stream in CMU

>•	The 'Mic' audio channel is the only transient focus event within the AA stream but since it is on the MLENT stream (which has focusType permanent) when it requests transient focus it is actually a transient stream within a permanent stream (and AA handles its own transient audio channels within its stream) so we will need to manually switch to MLENT to hear it 

Yeah AA seems to "upgrade" it's focus so if you already have permanent focus you don't get another event.

What about this? We register two sessions with the CMU audio manager and make two streams.  One "permanent" on MLENT and one "transient" on NAVIVOL (or some other type which has the right focus, a second MLENT if that's possible?). Then we could open three ALSA devices, two for media and prompts (the two AA streams on) device "entertainmentMl" and one on "informationNavi" for just the AU1 stream. Then if we have transient focus we switch to NAVIVOL and play on on informationNavi and if we have permanent focus we switch to MLENT and play to those two on entertainmentMl. This way the Notfy() events will get the correct focusType params and switching should work right for both types regardless of who initiates the events (us, AA, CMU, etc.)

I don't know if that will actually work though or not.

**Comment by Trevelopment** [comment]
I also rarely ever make phone calls either and I like to listen to my USB audio because it has 128 GB of music on a tiny little nub of a drive (which sometimes causes memory issues for me) and that's why I took AA down this fun little convoluted audio focus road.  So now that I got it this far might as well get it all wrapped up and working since you're probably like me in that we just like to make things work right!  Also, I definitely never use navigation prompts so I probably would have forgot to even consider that if you didn't put that comment in the code.

But that all sounds good with another stream and I think we may only need one additional stream to cover the 2 prompts.  So this would be like first make another AudioOutput device like 
`audioOutputTransient.reset(new AudioOutput("informationNavi")); //I think this is the stream to use for transient then we can use NAVIVOL or Navi`
Then use that for our second audio channel AA_CH_AU1.
Then we may not need to handle the transient streams farther than assigning them to the correct stream type.  They should be able to just request transient audio focus and give it back when complete.  The only thing we would have to watch for if we have permanent focus on AA or not.
Thats actually not that many changes I could probably bang that out and test it tonight

**Comment by lmagder** [comment]
I think I have fixed this! So ignoring transient focus worked, sort of but I got a solution which makes the mic prompts still work: I changed the code to actually register two MLENT streams, one with permanent focus and one with temporary focus, this makes the code a lot more robust since we don't need to track and magic state outside of the Notify() calls, this means other stuff can control the focus and we still get the right mode. This allows the BTHF to give up focus and have us end up back in the right mode we should be versus always getting permanent or something. The other clue I found was that on my PC where there is no BTHF stream but I had my phone connected to the PC via Ofono as BTHF, when I make a call through AA it still requests transient focus but that is never stolen by BTHF so at the end of the call AA gives up the focus correctly. It seems like the CMU stealing the focus to BTHF is confusing AA so when the CMU gives it back AA thought it was a fresh event and treats it as an intentional switch so it no longer fires the release focus message. The solution I found was to track the call status through the PhoneStatus AA message (maybe the car DBus works too, but this seemed more reliable if there are multiple phones involved etc.) and when there is a call going and the focus goes Transient MLENT -> BTHF and back just don't pass those messages onto AA so it thinks it has focus the entire time. Seems to solve everything based on my testing since it appears like AA considers BTHF as its audio with respect to focus events.

**Comment by Trevelopment** [comment]
Awesome I'll give it a test right now

**Comment by Trevelopment** [comment]
hey my in my initial test I could t make a call it just ended the call right away.  Looking at the log I notices even though you register 2 MLENT streams, AA never uses the 2nd one.  like it registered 27 & 28 and I noticed it says things like:
```
KEY_G
W: /home/mazda/headunit/hu/hu_aap.cpp:637: hu_handle_AudioFocusRequest : AudioFocusRequest Focus Request AA_CH_CTR: 2
audioMgrRequestAudioFocus(2)
requestAudioFocus({"sessionId":28})
{}
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"USB","streamModeName":"USB","newFocus":"lost","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 16 for stream USB
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","focusType":"transient","newFocus":"gained","destination":"Cabin","streamType":"Media"}
Found audio sessionId 27 for stream MLENT
AudioFocusHappend(2)
SHAI1 : Mic Started
SHAI1 : Mic Stopped
```
then this is what happened when I tried to make a call:
```
KEY_ENTER
W: /home/mazda/headunit/hu/hu_aap.cpp:637: hu_handle_AudioFocusRequest : AudioFocusRequest Focus Request AA_CH_CTR: 2
audioMgrRequestAudioFocus(2)
requestAudioFocus({"sessionId":28})
{}
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"USB","streamModeName":"USB","newFocus":"lost","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 16 for stream USB
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","focusType":"transient","newFocus":"gained","destination":"Cabin","streamType":"Media"}
Found audio sessionId 27 for stream MLENT
AudioFocusHappend(2)
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","focusType":"transient","newFocus":"temporarilyLost","destination":"Cabin","streamType":"Media"}
W: callbacks.cpp:544: Notify : Ignoring focus change due to call
W: /home/mazda/headunit/hu/hu_aap.cpp:637: hu_handle_AudioFocusRequest : AudioFocusRequest Focus Request AA_CH_CTR: 4
audioMgrReleaseAudioFocus()
requestAudioFocus({"sessionId":16})
{}
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"BTHF","streamModeName":"BTHF","newFocus":"gained","destination":"Cabin","focusType":"transient","streamType":"Telephony"}
Found audio sessionId 14 for stream BTHF
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","focusType":"transient","newFocus":"lost","destination":"Cabin","streamType":"Media"}
Found audio sessionId 27 for stream MLENT
AudioFocusHappend(0)
```

**Comment by Trevelopment** [comment]
Also the USB audio didn't start playing even though the log says it gained focus at the end of that.  The problem ay be because BTHF tried to take focus before MLENT released it and also I think MLENT taking focus like that between USB and BTHF is what pauses the audio.  
One more thing is I think you maybe can do what you are trying to do if you use one of the already registered transient streams as the 2nd stream.  There are a bunch maybe since its the mic you should use `SYSVR` or `BTRVR` on the `vrGeneric` alsa card.

**Comment by Trevelopment** [comment]
I am going to make a fresh binary and test it again looking at it again this might just be on me

**Comment by lmagder** [comment]
I think it should work, at least it did when I tested it on my car. There could be bugs though or stuff that's missing.

Responding to your comment, which I got an email notification but can't find on GitHub for some reason
>This seems like it wouldn't work to me because the system still handles the request for BTHF and will take focus from MLENT. By the time you get to this point the focus change so this just tells MLENT not to release focus for BTHF to take it.

It actually doesn't need to release it, it can be forcibly taken In the CMU the audio manager automatically remembers the previous stream when switching to a transient stream. There is an "abandon focus" request to audio manager which goes back to the previous one without the code needing to pass a specific stream. So what I think is happening or what is happening at least on my car when you make a phone call:

- AA requests focus for transient focus since it assumes that this also includes BTHF on the car
- This switches to transient MLENT and caches the previous active stream id in our code (we don't use the "abandonAudioFocus" request, maybe we should...)
- Actual phone call starts and CMU switches to BTHF from MLENT, internally it stores MLENT as the last stream. This triggers a "focus lost" event on MLENT which we were passing to AA
- Phone call ends, CMU calls abandonAudioFocus and the Audio Manager switches from BTHF back to MLENT (since that was the previous stream)
-  This triggers a "focus gained" event on MLENT which we were passing to AA.
-  AA sees this as an unconnected event where the car has asked it to take focus and leaves it that way, so the original audio doesn't return.

With this code what happens is this:

- AA requests focus for transient focus since it assumes that this also includes BTHF on the car
- This switches to transient MLENT and caches the previous active stream id in our code
- Actual phone call starts and CMU switches to BTHF from MLENT, internally it stores MLENT as the last stream. This triggers a "focus lost" event on MLENT, but we don't pass that on to AA, AA still thinks it has focus, and in a way it does.
- Phone call ends, CMU calls abandonAudioFocus and the Audio Manager switches from BTHF back to MLENT (since that was the previous stream)
-  This triggers a "focus gained" event on MLENT, but we ignore it since AA already assumes MLENT has focus
-  AA decides the phone call is done. Since you weren't playing media through AA it sends a message to release audio focus.
- We obey that message and switch back to the stream we cached when we got the request to take transient focus to MLENT
- Old audio USB/XM/etc. resumes.

Does that make sense? Or do I have something wrong? This worked on way on my end but I only tested making calls not receiving them. I found a test number (909) 390-0003 you can call which just echos back what you say which is useful for testing this without spamming friends and loved ones 😃

**Comment by Trevelopment** [comment]
yea man I don't know whats wrong but I tried 3 times to make a binary straight from your last commit but each time I try one in my car cannot make any calls (I was also only testing making calls) but when I go back to the old binary it works just fine... weird

**Comment by Trevelopment** [comment]
> It actually doesn't need to release it, it can be forcibly taken. 

Are you sure?? because I recall a Bluetooth call bug where BTHF could not forcibly take audio focus.
> Actual phone call starts and CMU switches to BTHF from MLENT, internally it stores MLENT as the last stream. This triggers a "focus lost" event on MLENT, but we don't pass that on to AA, AA still thinks it has focus, and in a way it does.

When you are listening to USB audio and you do this it stops the player and AA cannot resume USB music so you may get audio focus back to USB but you wont get any music playing.
Also I am pretty sure that the switch to MLENT when you make or answer a call confuses the CMU because it is trying to switch to BTHF but AA is already making one to MLENT at the same time so BTFH gets blocked (at least thats what it looks like is happening in my case).  That would make sense since both AA and the CMU are responding to the same request at the same time so what guarantees that MLENT is the first focus change and BTHF is the second?

> Phone call ends, CMU calls abandonAudioFocus and the Audio Manager switches from BTHF back to MLENT (since that was the previous stream)
This triggers a "focus gained" event on MLENT, but we ignore it since AA already assumes MLENT has focus
AA decides the phone call is done. Since you weren't playing media through AA it sends a message to release audio focus.
We obey that message and switch back to the stream we cached when we got the request to take transient focus to MLENT

These seem like unnecessary steps when we can just go from BTHF straight to stream without going through MLENT.  I can see that is all works kind of because it does switch back to the correct stream and if its not USB it starts playing again but why is it necessary?   The issue with me has to be the double audio focus change that's the only explanation I could come up with.
BTW I also cant make calls outside of AA when I install this binary so maybe something is keeping the mic on?  because that is what cause the bug last time right?
