### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by felipecorrea9** [gartnera/headunit#109]
Hi,
Im using v1.07 and Im getting random crashes while listening to music on Spotify or using Waze, GMaps o even after some calls.

Is there any way I could get some logs to see where the problem could it be and post some of that here?

Regards!

**Comment by Trevelopment** [comment]
the log is located @ `/tmp/mnt/data/headunit.log`

**Comment by mishaaq** [comment]
@felipecorrea9 are you sure it's a crash of the headunit process? I experience problems with AA crashing/falling into strange state from time to time since last month I believe. It is purely random - may happen after few minutes or not happen for hours. It starts from looping between acquiring and loosing video focus and after few times it dies. Reconnecting the usb cable does not help. Logs are empty when entering Android Auto app from CMU. You need to restart the phone (restarting some service in Android may help but I didn't try it driving 😃).
