### ISSUE TITLE
Versioning numbers

### ISSUE THREAD

**Issue by kungufli** [gartnera/headunit#114]
Just a clarification, I'm a bit confused: is the 1.05 version released few hours ago on this github repository more updated than the 1.07 version released on [mazdatweaks](https://mazdatweaks.com/androidauto/)?

**Comment by Trevelopment** [comment]
@lmagder I released a few versions with updates of AIO Tweaks that's why we've been getting a lot of feedback lately so you can jump to v1.08 I was about to release another update here in a few days with this AA update I'm just writing up the changelog I've got really solid updates on all the AIO apps.  The speedometer app was running 6 websocket connections at once!! I looked at it closely for the first time a couple weeks ago and said wait what is going on here?? you only need one of these!!1 now it runs like 100 times better.

**Comment by lmagder** [comment]
@trevelopment oops, my bad. Didn't realize what version we were up to.

**Comment by kungufli** [comment]
@lmagder @Trevelopment Thanks for clarifying the situation, and for all your work on this app.

**Comment by iainheng** [comment]
@lmagder @Trevelopment Great job in this 1.05 release. Just tested with my car and it works flawlessly. Google Maps navigation is so much faster now compare to previous release and bluetooth calls work beautifully too. 

Thank you all contributors for the great work 👍

**Comment by Trevelopment** [comment]
I noted the version discrepancy in the release comments
