### ISSUE TITLE
Reverse camara lost focus  cant find runing process back with fav button

### ISSUE THREAD

**Issue by carvajalluis** [gartnera/headunit#118]
I have been on and off  AA for Mazda, and don't get me wrong thank you very much for your awesome effort. older issues got me out fixes got me in back again  but now i have a reverse camera and  after succesfully conecting to the head unit with the cable conected to my cellphone,   to go out of my parking spot in reverse and then  the AA loses focus. is it me doing something wrong ?

**Comment by lmagder** [comment]
Which version are you using? It doesn't sound like anything is wrong on your end. It's likely there is a bug in handling the backup camera...again. 😞 Unfortunately not many of the developers have them so it gets broken often. My car does not, so I can't test it personally.

Do you have the log output from this sequence of actions? It might help. The backup camera focus hand-off is tricky and requires special handling in the code vs the normal CMU UI since both the backup camera and the AA view have to share the same video output surface in the OS since there is only one.

**Comment by mishaaq** [comment]
Ok, I'm a guy who originally fixed the issue with backup camera, but since then I've never experienced the issue again (running the current master) so I can't help with it neither.

**Comment by vincentbouillart** [comment]
I have the same issue :( as @carvajalluis

**Comment by carvajalluis** [comment]
I´m using the latest included in the https://mazdatweaks.com/ AIO, how do I  extract the logs to share them with you? so I suppose v1.07

**Comment by vincentbouillart** [comment]
i just get a black screen and no more :/

**Comment by mishaaq** [comment]
@vincentbouillart the backup camera wasn't handled at all so AA didn't release video when you chose reverse gear. This ended with displays from camera and AA interpenetrated.

**Comment by carvajalluis** [comment]
As it is now   i cant reproduce this bug anymore that is why i've been unable to share with you some logs

**Comment by lasantosr** [comment]
I have recently installed AA 1.8 and I have reverse camera + parking sensor.

When I put Reverse, reverse camera is shown, then I go back to N and the parking sensor is shown, when I disble it (pressing the physical button), MZD Home is shown, and i have to enter AA again, 
I've seen some video, where AA is opened again when Reverse Camera quits, but the video had no parking sensor...

Is there any logs I can send? and how to find them

**Comment by hrm701** [comment]
I also have the same problem
