### ISSUE TITLE
AA Notifications

### ISSUE THREAD

**Issue by Trevelopment** [gartnera/headunit#120]
@lmagder wanted to know if there is and API for AA notifications that we could use and if we could possibly use it through the command server to display notifications from the GUI.  I ask because I figured out how to have the song names display as SBN notifications on all the GUI screens it would be tight to be able to carry that over to AA.  And we could go the other way too with the info by @borconi in #16 I solved some of the massive edits to the JS part so we can use that to cross back and display SBNs and also it wouldnt be that tough to pass keys to AA from the GUI.   
Also I was wondering if you were aware of this: https://github.com/thekirankumar/youtube-android-auto 
http://www.thekirankumar.com/blog/2017/12/29/play-youtube-video-android-auto-app/
Dude is only 23 and he is just killin it.
I snagged a copy of the code while I still can because Google has already caught wind of it and want to block the app and he only been developing on it for like a month or so and it works pretty well.

**Comment by lmagder** [comment]
Yeah it could be interesting to hookup. It would be awesome to get track info for AA media when in CMU along with popups for directions. Also it would be great to see the current radio station and stuff in AA instead of just flying blind when you change channels. There is "generic notifications" AA api which I was trying to experiment with (you can see it in the code) but I never got anything working. I'm not even sure which direction it sends the notifications, CMU -> AA or AA -> CMU. I was hoping it was away to display events from the CMU on the AA UI, but I would settle for either.

If you have a way of adding a new audio app to AA without totally mangling the built-in music stuff I'm interested :) I guess the easiest way would be to display it in the current HTML UI we have but that wouldn't show up under the Music tab in the CMU UI correctly.

Yeah that guys work is cool. Especially the unofficial SDK stuff. (I don't feel a burning need to watch YouTube while I drive 💥 😆 ) It seems like we could make Android apps for debugging which just logs the car sensors or poke random APIs to send uncommon messages. Might be easier than trying to repro stuff only with Google Maps/Waze.

I think we could also use the vendor extension channel to send custom data between a custom Android app which could add a pane to the AA UI and the headunit process. Might be interesting for debugging and also adding new functionality stock AA doesn't support (eg a real settings pane with nice UI, browsing USB media, etc.)

**Comment by Trevelopment** [comment]
So what I figured out is basically just a MOD to the existing USBaudio app where I added a `startTimedSbn` to the `_ObjectInfoMsgHandler` function so that every time the data is retrieved at the start of each song, it shows a SBN of that info ("artist - song") and the trick I used to make it display is to tell SBN that the message is a `USBA_ConnectionStatus_SBN` and just pass the alternate text to display.  
What I was thinking was if we had a method in the command server to display notifications we could pass at the same time something like: `http://localhost:9999/notification?msg=artist%20-%20song` and that would display a notification in AA.
I was also more interested in the general work that guy did more than just the youtube functionality (because I don't really care to watch youtube while driving either) because I noticed that he uses the AA notifications when each youtube video starts.  So I was looking around his code (which is in Java) for the notification API to tap into but I was checking if you already looked into it which you have.
And going the other way we would just need to write a new function to handle AA messages like `AAMsgHandler` to handle incoming AA info and use the same trick to display whatever info you want to pass over.

**Comment by borconi** [comment]
I have fiddled around with the "Generic Notification" api quite a bit, I was able to pass correct messages from Headunit to AA, but nothing happened, I think I only saw some message in the Logs of the phone that there is no app to handle this, so I'll guess you need to have another app on the phone which can handles this "Generic Notification" 

It was a long time ago but I think it was unidirectional (from CMU to AA) and there wasn't a way to send data from AA to CMU.

Vendor channel extension can be used for detailed stuff ( VAG cars are using it - See https://github.com/martoreto/aastats )

Unofficial SDK is ok, I've been using it in a different form for a while - See OBD2AA app, but I did not share it to the public because I'm very much against creating apps like this YouTube Auto app.  If you want to find out more about the SDK, this is a much better place to look: https://github.com/martoreto/aauto-sdk-demo the examples are nice and clean, notification however has nothing to do with the car, it's something which works locally on the phone. 

As of the Radio part, the DHU (Desktop Head Unit) does contain code which relates the RDS/FM/AM but I never decoded that channel and I'm not even sure if it's a functional channel and even if it is, I'm not sure what will handle that on the phone side, because you will probably need to have an app which is AA compatible and can manipulate the Radio channel, however in the SDK for AA there is no trace of anything like that, so probably Radio control from within AA is currently not possible.

**Comment by Trevelopment** [comment]
Thanks for that @borconi you always have very helpful input and I use ODB2AA all the time.
There is actually a way in this headunit port to communicate back and forth from CMU to AA, the [command server](https://github.com/gartnera/headunit/blob/master/common/command_server.cpp) made by @lmagder. I'm guessing that is not something in other AA headunit apps but we may be able to use that to to one or both of these things:
1. Control AA music from outside AA
2. Get navigation and music notifications from AA to the CMU (And display with GUI SB notifications)
I think at least that much may be possible to do and I also think I want to start working on on android app that can support "Generic Notification" and that could also help bridge the communication between CMU and AA for Mazdas (possibly others too if I get that far).  
Of course, since it will be my first (finished 😬) Android app if I make it so it will probably take me a bit to get it rolling.  But I'm sure as long as @borconi is around for questions I'm pretty confident I could whip something up.  Like my first question is do you use any particular tools in your development or just Android Studio?  I used Corona before but my project got cut short because I got too busy with other things at the time but it was a lot easier for me to start a project with Corona, AS is almost overwhelming for a novice Android Dev but I am already starting to be a little more comfortable with it this time around.

**Comment by Trevelopment** [comment]
This cant be done through headunit only through an android app and all non-approved apps are blocked so this should be closed
