### ISSUE TITLE
App won't connect to phone "_startContextReady: Can't connect to headunit process"

### ISSUE THREAD

**Issue by QuillzLouis** [gartnera/headunit#122]
I installed the mod using the AIO Toolkit (2.7.6) and it installed correctly and opened for the first few times (using android auto app 2.9). I disconnected the phone from the car to install waze then reconnected and opened the Android Auto app on the head unit and got the error "_startContextReady: Can't connect to headunit process". I retried the process several times in the next few minutes (turning the car off each time and turning it on fully) and got the same error. How do I fix?

**Comment by vincentbouillart** [comment]
You can restart your system press back button + mute + nav for 20 secs and then it will work again

**Comment by gabe117** [comment]
I tried restarting the system and it worked the first time, but the next 2 times I turned the car on it wouldn't work giving the same error, and after restarting the system it still gave the same error

**Comment by Trevelopment** [comment]
Have you tried using a better USB cable?  Also, what kind of phone are you using?  The phone and cable have a lot to do with connection issues and 90% of the time a new cable will solve the problem. 
The other reason this may happen is because the headunit process did not install correctly.  In that case you can try to re-install or if you want to be more thorough you can uninstall and then re-install.   
That error you guys are getting means that either the headunit process never starts running or you crashed the headunit process and that happens a lot when you are using a bad USB cable but it can also happen for a ton of other reasons.  You need to do a hard reset like @vincentbouillart said that is the only way to get it going again (Or leave your car turned off for a long time like over 20 minutes.)  Simply tuning the car off for a second will not restart the process.  But if it never worked at all then it is probably the an issue with the installation.

**Comment by QuillzLouis** [comment]
I tried the hard restart and it worked. Thanks :)

**Comment by pgiduthuri** [comment]
I installed AA MZD-AIO-TI 2.7.8 on 2016 Mazda 6. Everything works fine when connected once.
But if I take off and on, it does not work back again and shows **_startContextReady: Can't connect to headunit process"**

If I hard reset [ Nav + Mute ], it works again. Any help.

Phones used are Samsung S8+ & Note 8.

I installed only AA with Enable WIFI and Install SSH_bring back.

appreciate any help on this please

**Comment by gabe117** [comment]
@pgiduthuri Did you get an error when installing? I did, and have the same issue as you. 

I was going to try to install AA using AIO instead, but I haven't tried it yet

**Comment by pgiduthuri** [comment]
I got to install perfect, and it worked one time.
when I plug out and plug in the cable again, the problem starts.

**Comment by pgiduthuri** [comment]
I think no one got to work it 100%.
