### ISSUE TITLE
AA doesn't reboot if phone is left plugged in - Error "can't connect to headunit process"

### ISSUE THREAD

**Issue by PandaJungle1** [gartnera/headunit#128]
Android Auto doesn't restart if the car/infotainment unit is rebooted with the phone plugged running AA.  Not a big issue, but this happens if you need to stop the car for a couple of minutes and then need to restart the car to keep driving. 

Steps to reproduce.

1. Plug in phone and start the car.
2.  Phone AA auto starts  and Mazda AA auto starts. Everything works fine.
3. Turn off the car/infotainment unit while AA is plugged in.
4. Immediately turn the car/unit back on. The unit wakes up very fast as if it was just sleeping
5. phone AA auto starts, but the Mazda AA does not and when you run AA it shows the credits and  "can't connect to headunit process".

Ways to fix problem

1. Turning off the car for > 5 minutes so the unit completely turns off.
2. Soft reboot by holding Back, Nav, Mute button for 10 seconds.

FW: 55.00.753
Mazda AIO: 2.7.8
AA Headunit App: 1.08
Phone: Samsung S7 Edge

Two other users have the same issue: 

http://mazda3revolution.com/forums/2014-2017-mazda-3-skyactiv-audio-electronics/122458-aio-all-one-tweaks-541.html#post2250082

**Comment by mishan** [comment]
I have had this happen to me in various edge cases -- always involving quick power down of the car or perhaps a quick unplugging of the phone or something.

My theory is that some edge cases cause the headunit process to crash, and it doesn't resume after a crash. I haven't had the chance to verify it, though a simple verification would be as follows:

(1) Reproduce problem where you get this error message
(2) SSH into your CMU
(3) Run "ps aux | grep headunit" and see if headunit is indeed running.

It should be pretty easy to add code somewhere, or run headunit via some supervisor program, to ensure that headunit is restarted after a crash so that a reboot of the Infotainment system is not required.
