### ISSUE TITLE
Incompatible with V59.00.330 EU N

### ISSUE THREAD

**Issue by petrepopescu21** [gartnera/headunit#25]
I have a 2017 Mazda 6 with CMU version 59.00.330 EU N

I tried installing v0.94b

I followed the install steps on the releases page and it went well until the restart part. The CMU restarted fine, although AA did not show up in the applications list.

**Comment by camilok14** [comment]
Same problem here on Mazda 3 2017 with Version 59.00.330 4A N

**Comment by dherby** [comment]
Same issue with 59.00.441 NA N :(

**Comment by lmagder** [comment]
Since the app doesn't show up at all I bet it's something wrong with the registration in 59 and maybe not the headunit part. Maybe the DriveChartDetails app it replaces is gone? I'm not sure since I have v56.

The code is here: https://github.com/lmagder/headunit/blob/master/mazda/installer/config/androidauto/jci/opera/opera_dir/userjs/additionalApps.js

gartnera includes this in the release packages but it's not in the main repo. I checked into my repo just for reference.

Does anyone have a filesystem dump of 59 they can examine and post the systemApp.js from it?

**Comment by manuelnelson** [comment]
I'm a bit of noob, how can I get a filesystem dump?  I have the same problem and would be willing to help out best i can.

**Comment by lmagder** [comment]
you could try this tool: http://mazda3revolution.com/forums/2014-2016-mazda-3-skyactiv-audio-electronics/57714-infotainment-project-457.html#post1581386

not sure if it works on 59 though. Essentially you can edit the tweaks.sh file to do whatever you want, like with this package it just copies the entire filesytem to the usb using shell commands, but you could do similar by replacing the tweaks.sh in the AA installer.

**Comment by kmark** [comment]
Here's [systemApp.js](https://github.com/gartnera/headunit/files/611226/systemApp.js.txt) for 59.00.441A NA. New to this but I see references to CarPlay and Android Auto. Looks like Mazda has pushed some of their work out. I wonder if changing `visible` to `true` would let us take a peak...

**Comment by lmagder** [comment]
Sorry guys, my char as v55 on it so I'm afraid I can't help much with this. If somebody has a v59 car and want's go over the install scripts and js files in https://github.com/gartnera/headunit/tree/master/mazda/installer with a fine tooth comb, we can probably figure out what's incompatible with v59. If it's not appearing the in the menu at all my hunch is something related to the JS portion.

**Comment by paradexes** [comment]
I have v59. And its possible switching that systemApp.js to true would be what does it. I am fairly new to this and I'm willing to take the plunge. where would I drop this file? Can I add it using the tweaks.sh? If so I can add the line, just need to know what should go in there.

**Comment by edgargonzalez17** [comment]
@paradexes did you manage to do this? i have v59 too and im willing to try this out.

**Comment by edgargonzalez17** [comment]
@kmark @lmagder can someone tell me how to modify my systemApp.js?

**Comment by paradexes** [comment]
@edgargonzalez17 I never got it to work. Most other things in the AIO seemed to work. Hopefully someone sorts this out. Be nice to have this actually working. I installed a new after market system on my wife's CX9 (2013) w/android auto, so that would be a nice to have for my 2016 CX5.

**Comment by edgargonzalez17** [comment]
@paradexes  but did you try setting Android Auto to true in the systemApp.js?

**Comment by paradexes** [comment]
@edgargonzalez17 yes I did. Did not work. IF it installed, there was no way to start it from the apps menu.

**Comment by felipecorrea9** [comment]
I have 59.0.0.330A-ADR and it works fine. I just cant make calls.

**Comment by lmagder** [comment]
I think the Android Auto setting in ssystemApp.js may be a decoy. Possibly a half-finished implementation by JCI that was never enabled?

I can't really do much from my end since I only have a 2016 NA car with 55 on it. But if you guys want to delve all the relevant code is in here: https://github.com/gartnera/headunit/tree/master/mazda/installer/config/androidauto/jci

The app is split into two parts (well 3 technically if you include input_filter) but 95% of it is C++ code what runs as normal Linux processes. The JS code I linked to, all it actually does is add a menu item to launch the headunit binary. The CMU "app" is just a static html page and the other app renders fullscreen covering it.

It seems like maybe that's the only part that's broken? They could have changed the JS-based API in some versions of 59. If somebody has a dump of the OS from a non-working v59 they could compare some of the built in apps in /jci/gui/apps with the code in our "_androidAuto" app and see if something about the interface has changed.

**Comment by edgargonzalez17** [comment]
@paradexes can you provide this dump?

**Comment by edgargonzalez17** [comment]
@lmagder im up to test and provide you everything you need to get this working, you can write me if you want. edgar.gonzalez17(at)gmail(dot)com

**Comment by paradexes** [comment]
I'll try to pull it this weekend. I believe the AIO tool has a backup JCI tool correct? If so I'll use that, otherwise I may need someone to walk me through this.

**Comment by edgargonzalez17** [comment]
well, didn't worked for me either, @gartnera can you please give us some directions on what to do to get this working? thank you.

**Comment by Borillion** [comment]
I have 59.00.441 , will try and take a dump also.

**Comment by edgargonzalez17** [comment]
@Borillion can you tell me how to take the dump files?

**Comment by Borillion** [comment]
I am using this zip file as a guide here but going to do it manually, http://mazda3revolution.com/forums/1581386-post4563.html

**Comment by jason300x** [comment]
i tried installing AA with newest AIO v2.2.1 and still doesnt work . 
here are logs. I guess problem is that somehow AA already exists in additionalApps but that is just a big guess.


INSTALL ANDROID AUTO HEADUNIT APP ...
=== Begin Installation Of Android Auto Hsadunit App ===
=== Copied Headunit Files ===
=== Backup of /usr/lib/gstreamer-0.10/libgstalsa.so to libgstalsa.so.org ===
=== Clean obsolete input_filter to /jci/sm/sm.conf ===
=== Copied Android Auto Headunit App files ===
=== 1st line of stage_wifi.sh is OK ===
=== Backup of /jci/scripts/stage_wifi.sh to stage_wifi.sh.AA ===
=== Added Android Auto entry to /jci/scripts/stage_wifi.sh ===
=== No additionalApps.js available, will copy one ===
=== Android Auto already exists in additionalApps.json, no modification necessary ===
END INSTALLATION OF ANDROID AUTO HEADUNIT APP
 
 
=============== END OF TWEAKS INSTALLATION ===============

**Comment by edgargonzalez17** [comment]
You need to install NO_MORE_DISCLAIMER from Aló 2.2.1.

**Comment by edgargonzalez17** [comment]
AIO 2.2.1*

**Comment by jason300x** [comment]
I did that according to manual - but with parameters to reduce time to 0.5 instead of 0

**Comment by jason300x** [comment]
And still not working to be clear

**Comment by jason300x** [comment]
i installed again with AIO 2.2.2 with no more disclaimer (reduced to 0) after previously uninstalling all tweaks(AA and NO MORE D.) and still AA is not on app list.

I attach zip file with logs + full backup of jci folder - before any tweaks done on 59.00.330 EU

you can download it from my google drive.

https://drive.google.com/file/d/0B9mPP5b2VDH9Rm9rNzd6cWtzSnM/view?usp=sharing

**Comment by kbojarcz300** [comment]
i think its already solved in AIO 2.2.4 . It works on my mazda 59.00.330 EU

**Comment by paradexes** [comment]
Yea AA still is not working for me on AIO 2.2.4. V59 NA (don't have minor number handy, I'll have to look). The update really changed nothing for me.

**Comment by naz1911** [comment]
I installed EU 59.00.443C on my Mazda 6 UK edition. I used AIO 2.3.7 to install AA but "Real" issue now is that bluetooth phone calling wont work from within AA. Keeps saying connect phone via bluetooth on a blue background.

**Comment by kbojarcz300** [comment]
it never worked for me, had to close AA always. that's the problem with this version. few days ago i had major crash of AA. My mazda infotainment didn't move for 10 minutes, even after car restart.
Then it suddenly started moving. After all that i decided it's not time to use this tool. 
It's just not worth going to mazda dealer screaming for help (it possibly costs you both money and warranty).

**Comment by creativekindle** [comment]
@kmark how did you get the systemApp.js file? Looks to me you're exactly right - AA is installing but line 686 of systemApp.js is hiding it in the application list... isVisible : false

I'm also on 59.00.441A NA and would like to help.

**Comment by kmark** [comment]
@creativekindle Used an SSH server run automatically off a USB drive. That is, as far as I can tell, a fresh systemApp.js from 59 NA. I have not yet tried to install the custom Android Auto stuff yet. That means that the entries for CarPlay and Auto are actually from Mazda.

**Comment by Trevelopment** [comment]
This issue has been way fixed in AIO.  I could add the fix in a commit here the only thing is copying the patched systemApp.js will potentially remove other tweaks that may have been made in that file ie no more disclaimer and order of audio source list tweaks.  There is too much changed code for me to be comfortable using sed or a similar command to replace chunks of code so using AIO to get the proper patched file is the solution so I think this issue should be closed.
