### ISSUE TITLE
screen corrupts when backup camera turns on

### ISSUE THREAD

**Issue by mishaaq** [gartnera/headunit#48]
I've compiled and installed current HEAD version (commit [d0706eab21dbac9fca2ca3c967ded59e9faf1da6](https://github.com/gartnera/headunit/commit/d0706eab21dbac9fca2ca3c967ded59e9faf1da6)). When going reverse the screen goes corrupt - it displays something like a combination of two surfaces: the camera and Android Auto. Probably the headunit should "release" the screen somehow or TV_TOUCH_SURFACE is not the right one?

**Comment by izacus** [comment]
Hmm, I've noticed this regression as well after removal of input filter (also AA crashes after a few moments with backup camera active), we probably don't release the video soon enough.

**Comment by lmagder** [comment]
I don't have a backup camera so I'm afraid I can't repro or test a fix, but would accept pull requests 😄 

My hunch is you are on the right track @mishaaq. TV_TOUCH_SURFACE  is correct for us since that's where the HW accellerated video output goes, but I think it's also where the backup camera goes (maybe they are both using similar paths for video)

Unfortunately the com.jci.nativeguictrl DBus interface doesn't have any signals or way of querying the current surface, only setting which is why the unfocusing code sets a hardcoded surface list instead of what was previously focused. Maybe there is someway of getting this? 

I also noticed the com.jci.bucpsa interface we are connecting to with BUCPSAClient has a ReverseStatusChanged signal in addition to the DisplayMode one we are using. Maybe calling MazdaEventCallbacks::VideoFocusHappened from there would do the trick? But probably we would also need to check if the backup camera is present and enabled.

**Comment by davepro305** [comment]
If it can help you, it comes back to normal when there is a new action or a new info to be displayd. Like if sporify is running, the corruption will be there only for 1 sec, the time that the screen "refreshes" because of the timeline of the song playing. Corruption will also disapear if you press where the bottom buttons are and you switch the apps. So yes, probably a screen refresh will do the trick. Hope it helps.

**Comment by mishaaq** [comment]
@davepro305 I don't know what exactly you mean by "comes to normal", but in my case the screen is corrupted (colors are mixed) as long as I go back to native UI or change gear (I'm kicked out of AA/Backup camera screen then).

**Comment by gartnera** [comment]
So someone removed my backup cam workaround at some point which was this:

`g_object_set(G_OBJECT(app->sink), "should-display", FALSE, NULL);`

when switching to the backup cam and 

`g_object_set(G_OBJECT(app->sink), "should-display", TRUE, NULL);`

a few ms after the backup cam had stopped.

Did you figure out another way of doing it?

Basically I patched the mfw_isink.so lib to drop frames. There was a little corruption, but it worked alright. I have a copy of the source laying around somewhere, I'll post it if I find it.

**Comment by lmagder** [comment]
Ah I didn't release that's what that was for. I thought it was some kind of screen sleep mode or something not realizing that BUC == "Back up camera" 🤦‍♂️ 

There is code to handle that signal still, but I think I have the logic reversed. I assumed currentDisplayMode was for screen on, not backup camera showing

https://github.com/gartnera/headunit/blob/master/mazda/outputs.cpp#L416

It actually destroys the entire gstreamer pipeline and then recreates it when video focus is gotten/lost as well as telling the phone to stop sending frames, so I'm not sure if the frame-dropping hack is still required, but we are still using the custom sink either way.

However the VideoOutput destructor does set the surface back to JCI_OPERA_PRIMARY which is maybe not desirable in this case. BUCPSAClient::DisplayMode could set it back to TV_TOUCH_SURFACE though.

**Comment by borconi** [comment]
Guys normally you should send a VIDEO FOCUS LOST signal to Android Auto, which will halt/stop the video stream and when you're back in the app you have to send another VIDEO FOCUS GAIN notification.

related protobuf:

```
enum MessageTypeMedia
{
    MSG_TYPE_MEDIASETUPREQUEST = 0x8000;
    MSG_TYPE_MEDIASTARTREQUEST = 0x8001;
    MSG_TYPE_MEDIASTOPREQUEST = 0x8002;
    MSG_TYPE_MEDIASETUPRESPONSE = 0x8003;
    MSG_TYPE_ACK = 0x8004;
    MSG_TYPE_MICREQUEST = 0x8005;
    MSG_TYPE_MICREPONSE = 0x8006;
    MSG_TYPE_VIDEOFOCUSREQUESTNOTIFICATION = 0x8007;
    MSG_TYPE_VIDEOFOCUSNOTIFICATION = 0x8008;
};

enum VideoFocusMode
{
    VIDEO_FOCUS_MODE_1 = 1;
    VIDEO_FOCUS_MODE_2 = 2;
}

message VideoFocusNotification
{
    optional VideoFocusMode mode = 1;
    optional bool unsolicited = 2;
}
```

Alternativelly you can use the following byte array:
```
byte rsp2 [] = {0x80, 0x08, 0x08, 1, 0x10, 1};    // Focus Gained
byte rsp2 [] = {0x80, 0x08, 0x08, 2, 0x10, 1};    // Focus Lost
```

So make sure when your app switched to reverse camera you send this to the phone to destroy the video stream and of course restart it when you return to the app.

**Comment by ryoncy** [comment]
@mishaaq i also facing same issue when going reverse the screen goes corrupt, how to fix it?

**Comment by mishaaq** [comment]
@ryoncy we are working on it

**Comment by ryoncy** [comment]
@mishaaq can you share to me complete installer for this fixed version, and can you teach me how to compile new installer. Thanks

**Comment by mishaaq** [comment]
@ryoncy installer is not compiled, only the headunit binary. Just copy entire `mazda/installer` directory to the USB drive.
Before that you have to compile the binary running `make` followed by `make install` in the `mazda/` directory. It is required to install some development packages on the machine beforehand: alsa-dev, libssl-dev, libusb-dev and few gstreamer- ones, don't remember exactly. Try running `make` and it tells you more or less what is missing.
@lmagder It would be nice to update the readme file, what do you think?

**Comment by ryoncy** [comment]
@mishaaq can you share to me latest installer?

**Comment by mishaaq** [comment]
@ryoncy http://www.megafileupload.com/268it/aa_installer-5ef71ea.zip
Please make notice that it includes new installer with the "update/uninstall" feature and it **must not** be used on existing AIO installation - removing AA in this case will break other tweaks and apps.

**Comment by ryoncy** [comment]
@mishaaq i copy to USB drive and try install, but not working and never show installation progress.
