### ISSUE TITLE
AA Stuck on credits 

### ISSUE THREAD

**Issue by edgargonzalez17** [gartnera/headunit#50]
i installed AA in my 2017 Mazda 3 v59, i connect my phone to BT and USB connection, but when i open AA, it gets stuck in credits, and never pass through.

I already tested with Nexus 6P and Galaxy S6. No luck.
What can i do?

**Comment by SolomonRodion** [comment]
I have the same problem: _startContextReady: Can't connect to headunit process.
But older version that I downloaded 2 weeks ago opens well

**Comment by edgargonzalez17** [comment]
@SolomonRodion can you specify that version?

**Comment by SolomonRodion** [comment]
i don't know the version but i downloaded it at 01/30/17

**Comment by edgargonzalez17** [comment]
@SolomonRodion btw, where do you get this error?

**Comment by SolomonRodion** [comment]
I see the error message when i try to execute Android Auto in MZD so I see half display is credits and half display is black with the message

**Comment by lmagder** [comment]
Can one of you guys post your installation log? It should be on the USB key after installation.

**Comment by SolomonRodion** [comment]
While installing there was a message on the screen: "Headunit binary can't launch. Check the log"
There are AIO_log.txt:
=== START LOGGING ... ===
=== MYDIR = /tmp/mnt/sda1 ===
=== Copytest to sd card successful, mount point is OK ===
= POPUP: Version = 56.00.230A-EU : To continue installation press OK 
=== Watchdog temporary disabeld and write access enabled ===
=== Killing running headunit processes ===
=== Backup of /jci/opera/opera_home/opera.ini.org already there! ===
=== ENABLED USERJS AND ALLOWED FILE XMLHTTPREQUEST IN /JCI/OPERA/OPERA_HOME/OPERA.INI  ===
= POPUP: INSTALL ANDROID AUTO HEADUNIT APP ... 
=== Copied Android Auto Headunit App files ===
=== Backup of /jci/scripts/stage_wifi.sh to stage_wifi.sh.bak===
=== Modifications added to /jci/scripts/stage_wifi.sh ===
=== END INSTALLATION OF ANDROID AUTO HEADUNIT APP ===
=== RUNNING TEST RUN ===
taskset: can't execute '/tmp/mnt/data_persist/dev/bin/headunit': No such file or directory
= POPUP: Headunit binary can't launch. Check the log 


As I understood is missing file 'config\androidauto\data_persist\dev\bin\headunit'

**Comment by edgargonzalez17** [comment]
i lost my logs and backups, im willing to install AA again, but i don't know if it is safe to perform an uninstall. if @lmagder confirm it is safe i can reinstall and post the log.

**Comment by lmagder** [comment]
@edgargonzalez17 unfortunately the uninstaller isn't ready or really tested yet, but it's safe to reinstall on top (I do it all the time to test new builds)

That "can't execute '/tmp/mnt/data_persist/dev/bin/headunit': No such file or directory" error is pretty generic unfortunately. It could be mean the file is missing which is unlikely since it was just copied there by the script, or also that a shared library or symbol in a shared library we expect to be on the car is not there. Linux is extremely non-specific here whereas windows would say "Can't find 'something' in some.dll"

If one of you guys with v59 can, can you dump a list of the files in /lib and /usr/lib on the car? Or even better, if you have a dump of the CMU OS on your PC, run the cross tools ldd on your dump and the headunit binary. 

Probably like `./m3-toolchain/bin/arm-cortexa9_neon-linux-gnueabi-ldd --root <yourdump> ./headunit` or something.

**Comment by edgargonzalez17** [comment]
How can i get this list of files? @lmagder

**Comment by edgargonzalez17** [comment]
Btw, several people are saying that they get it to work installing them from AIO, i was wondering if there was any difference or its the same installation. I installed mine from release section of this repo. @lmagder

**Comment by lmagder** [comment]
@edgargonzalez17 you can actually replace the tweaks.sh with any shell script you want to run. The code `MYDIR=$(dirname $(readlink -f $0))` gets the path to the usb key so you can run commands and pipe their output to files there to look at them. That's how I got my file dump actually I wrote a script to tar everything and put the tar file on usb key. Just be careful since it runs as root 😨 

About, AIO: I'm not sure. I noticed some of the AIO guys have integrated some of our recent changes into their repo, but I haven't been coordinating with them or anything. I'm also not sure the history of some of the files in the project, specifically the JS code since it was here when I got here. It's possible one of the other guys who are no longer active may have forked an old version of AIO code and the AIO guys have since fixed compatibility with newer OSes upstream?

**Comment by edgargonzalez17** [comment]
thanks @lmagder , will try to get the list.

btw, there's a new update on AIO and this is the change log:

```
Android Auto V1.2 Update - By: Khantaena

"Android Audio" Menu Option No Longer Starts The Process, Instead It Tells The Phone To Ask For Video Focus Again If You Have Pressed The Physical "Home" Button And Left The AA UI.
Refactor Code Into A Long-Running Service That Starts On CMU Boot. Allows Auto-Start On Phone Connection.
Fix Bug In Focus Handling When The Audio Focus Is Lost Externally. No Longer Gets Stuck Unfocused
Audio And Video Focus Can Now Be Gained/Last At Will And Restore Previous Focus. This Allows You To Play The Radio But Also Receive Navigation Prompts (For Example) Or Use The CMU UI While Playing Music Via AA.
```

i've been searching on internet about this version by Khantaena and couldn't find anything. Do you know anything about that? i would like to try it, but im not sure if it is compatible with your version.

**Comment by SolomonRodion** [comment]
When I try exec by ssh '/nmt/data_persist/dev/bin/headunit' it works well but I can't run it by addition applications in Media System - error: "Can't connect to headunit process"

**Comment by lmagder** [comment]
@edgargonzalez17 Those changes seem familiar 😄 I think those guys are cherrypicking commits from this repo, which is totally fine (it is OSS after all) but it makes the comparison a little murky. Probably there are compatible, but I'm not sure what they have changed. It might be interesting to diff their and our HEAD since maybe there are fixes we should upstream.

**Comment by edgargonzalez17** [comment]
@lmagder couldn't find their repo, did you find it?

**Comment by lmagder** [comment]
@edgargonzalez17 I think it's this one: https://github.com/khantaena/headunit and https://github.com/Trevelopment/MZD-AIO-TI
