### ISSUE TITLE
Steering wheel track audio commands Bluetooth device not Android Auto via usb

### ISSUE THREAD

**Issue by Jinmcx** [gartnera/headunit#52]
Similar to .93 the steer wheel audio button commands the Bluetooth device but in the latest test version it control the android auto via usb. I might be one of those rare people that uses android auto device (stationary) and a mobile device (personal smartphone Android/iPhone) and listen audio on my phone cause of unlimited data. 

Not essential but I think it be very helpful considering if you do use android auto and audio you would be command via bluetooth.

Hope that makes sense.

Test version: #40 #40 Command

**Comment by lmagder** [comment]
I think this is possible, but with the non-input filter input handling we get **all** the input events and can't optionally pass them on, so we need to manually generate the next and back input messages to the mmui socket interface when the phone doesn't have audio focus.

**Comment by Trevelopment** [comment]
hey @lmagder, do you have an idea of how we could pass the input messages to the mmui?  I set up the next and prev buttons to use different scanCodes depending on if AA has audio focus or not but my simplistic attempt to accomplish this didn't work. Here is I did and it works in the sense that if AA doesn't have video focus the buttons don't do anything. in outputs.cpp:
```cpp
bool hasAudioFocus = callbacks->audioFocus;
 ...
 ...
case KEY_LEFTBRACE:
    printf("KEY_LEFTBRACE\n");
    if (hasAudioFocus) {
      scanCode = HUIB_NEXT;
    } else {
      scanCode = KEY_LEFTBRACE;
    }
    break;
case KEY_RIGHTBRACE:
    printf("KEY_RIGHTBRACE\n");
    if (hasAudioFocus) {
      scanCode = HUIB_PREV;
    } else {
      scanCode = KEY_RIGHTBRACE;
    }
    break;
```
So this is a simplistic view because obviously AA is still capturing the KEY_* in those cases so how could we do this?  Use callback method to pass the KEY_* press to the MMUI?  I thought you may have some insight on this.

**Comment by Trevelopment** [comment]
#94 @lmagder no need for mmui socket just use uinput to press a virtual keystroke
