### ISSUE TITLE
Should the installer script remove input_filter service if it is found?

### ISSUE THREAD

**Issue by bdr99** [gartnera/headunit#56]
Some users may be running an old version that included the input_filter service which I have heard, if installed, can cause bricks when the system is factory reset. Would it be a good idea for the script to remove this if found, since it is dangerous and no longer necessary?

**Comment by lmagder** [comment]
I'm not sure the risk vs. reward makes sense to do this. I think it should leave it alone. 

The last few versions of AA didn't automatically enable the input_filter service since @gartnera found editing sm.conf was very brick-prone, so the only people who have it are those who manually installed and then upgraded to the current version. Starting fresh with the current version you would never have had it and there is no need to touch sm.conf at all anywhere in our scripts.

So there are basically three cases:

1. Fresh install with new system: There is no input_filter anywhere
2. Upgrading from old install: input_filter binary is there but not run (since old installer doesn't modify sm.conf)
3. Upgrading from old install with manually edited sm.conf: input_filter runs but does no harm (I tested this case)

In case 3 we could add code to parse sm.conf to remove input filter, but if we mess up somewhere it will brick the car. What's the gain here? leaving input_filter is fine and if people want to remove it they are also the people who manually edited sm.conf to add it, so they can do that again to remove it 😃 

Unless I'm missing another reason?

**Comment by ignabel** [comment]
Maybe I'm wrong but if I remember correctly, one of the installers (I think 0.92a) installed the input filter by default.  The installer also backed up sm.conf to sm.conf.org. In my case it had very few changes ([more info here](http://mazda3revolution.com/forums/2014-2017-mazda-3-skyactiv-audio-electronics/121561-android-auto-headunit-app-beta-81.html#post1808937)). In case this is helpful to anyone, to remove the input filter I deleted lines 24 and 99 from my sm.conf file.

sm.conf	line 24: <service type="process" name="input_filter" path="/tmp/mnt/data/input_filter" autorun="yes" reset_board="no" retry_count="0" affinity_mask="0x02"></service>

sm.conf	line 99: <dependency type="service" value="input_filter"/>
