### ISSUE TITLE
AA Uninstaller script not removing AA completely

### ISSUE THREAD

**Issue by Jinmcx** [gartnera/headunit#57]
The AA uninstaller script isn't moving AA completely. After using the uninstalling and installing .93 I couldn't make phone calls. I had to open AA and close (return to MZD) to make phone calls. I have to consistently do that... Trying to get back to stock .93 thus I know some script is being left over.

**Comment by lmagder** [comment]
Which commit # are you using?

I haven't been able to repro this. Do can you find more information about what files are left behind? The uninstaller in HEAD right now removes all the files it adds and undoes everything it does. My car might not be a good test though since I have been continually upgrading as I develop so maybe the bug is related to 0.93/0.94 -> head.

**Comment by Jinmcx** [comment]
Sorry for not being clean I been using the uninstaller by gartnera https://github.com/gartnera/headunit/releases/download/v0.91B/AA_Uninstaller.zip . I didn't know there was a new uninstaller. It's a persistent issue with the old installer at least cause I can't seen to make call unless if I open up AA and close it on .93 .

**Comment by lmagder** [comment]
My comment in https://github.com/gartnera/headunit/issues/54 has the new uninstaller script.

The old uninstaller works for v94 and under, but the new one has it built into the installer

**Comment by Jinmcx** [comment]
Great resolved didn't know it was in the installer!
