### ISSUE TITLE
Android Auto FM Radio

### ISSUE THREAD

**Issue by e1ace** [gartnera/headunit#59]
I was just wondering if there is a possibility of having an android music app which has the ability to change the Mazda's audio options (between bluetooth and FM radio)? 

Is this level of integration into the car possible with android auto?

Feel free to close/delete this if it is not the appropriate place for this discussion.

**Comment by izacus** [comment]
The old input filter allowed switching between Bluetooth and FM radio by pressing star, but I think that functionality has now been temporarily removed.

Android Auto also has "sensor" where it can receive data about current FM station which means that at least some integration is planned by Google, but I'm not sure if it actually allows control of it at this point.

**Comment by lmagder** [comment]
Yeah I haven't tried hooking up the radio messages in the protocol but it's on my list of stuff to try since I listen to XM radio a lot while driving. I hope it actually does something on the phone side :) but it should be easy to test on PC by enumerating fake radio stations.

 Right now you can listen to FM and stuff but to change channels you need to press home to exit, then re-enter the AA app. Unlike before this doesn't disconnect so you still get navigation prompts and the phone knows you can't see the screen so it's ok but not ideal IMO.

I think this would be mitigated a lot by passing forward the next and previous track steering wheel buttons to the CMU when AA doesn't have audio focus (https://github.com/gartnera/headunit/issues/52) that way you could change stations and tracks without navigating out of AA. The problem is that with the non-input-filter method for getting input, it's an all-or-nothing thing so we would need to interact with the mui socket events to sent the global next and previous track events, which currently the code doesn't. Although it should be possible.

**Comment by borconi** [comment]
At the moment the AA interface which can operate the FM/dab module on the unit itself, it's not yet functional.... So need to wait till AA actually implements it.
