### ISSUE TITLE
Make a 0.95 release

### ISSUE THREAD

**Issue by izacus** [gartnera/headunit#60]
People are still downloading version 0.94A which is very old now and doesn't have any of the cool stuff contributed by @lmagder and others. This also generates bunch of complaints.

Should we package the installer and current master into a `0.95` release under downloads here so people stop downloading old stuff? :)

**Comment by vicbam85** [comment]
Please correct the bug of making and receiving calls using the native gui. With the last "betas" in github they were redirected to the phone (as happened in previous versions but only inside AA).

Thanks for all the effort

**Comment by Jinmcx** [comment]
I like .93A :[.

**Comment by ryoncy** [comment]
I agree with release 0.95 too.

**Comment by davepro305** [comment]
Yes please!! :)

**Comment by bdr99** [comment]
I think the only major problem with the current version is that it prevents phone calls from working at all, even when AA is not running (#53). I think if this could be fixed, then we would be ready for a release.

**Comment by lmagder** [comment]
Yeah, I agree we are pretty deep in here with no release and that the bugs filed on the current releases are not so useful anymore.

I was kind of waiting for two things before releasing:

- Somebody with a backup camera to verify that my changes to @mishaaq 's code in https://github.com/gartnera/headunit/pull/49 actually work
- Fixing https://github.com/gartnera/headunit/issues/53

https://github.com/gartnera/headunit/issues/53 is tricky since with the new architecture the phone is always in AA mode when connected. This allows you to navigate in and out of the AA interface while using navigation and media stuff but it also means that the phone expects that the car side of the AA protocol works. At least that's my theory since nothing on the car side has changed other than reporting the BT address when connecting.

**Comment by izacus** [comment]
Hmm, #53 might be connected to the fact that AA now runs constantly in the background (or at least seems to pop up automatically when I connect the phone). We can disable the BT service for now anyway, since it's not useful until we fix #2 at all.

I've tested backup camera and it's working (including just the front sensor overlay), but AA seems to crash in the background sometimes, or just ends up returning to a black AA screen. Still something funky going on there, I'll investigate when I get a bit more time (spring will make it easier! ;) )

**Comment by restrepogoez** [comment]
CMU V56.00.513 ADR, backup camera works excellent

**Comment by iainheng** [comment]
Yes. A new release is definitely needed once #53 is fixed

**Comment by naz1911** [comment]
Definitely. A release that fixes the bluetooth phone call issues would be really good.

**Comment by goon818** [comment]
Can you give me the downloadlink for the 0.95? I would try it.
I search on all Github, who i know and i can't found it
Can you look in the code of the Headunit Mod. I mean, the Audio are transportet over USB and not over Bluetooth. I mean, Alex done this because he mean the audio it stuttering more over bluetooth as over usb. As the first issue, i would change the audio source to Bluetooth. You see, that the audio are transportet over usb on this function.  You can not change the loudness.

**Comment by ryoncy** [comment]
@lmagder is it can release a new version since the phone call issue fixed.

**Comment by Trevelopment** [comment]
Here you go guys AA v1.04 release: https://github.com/gartnera/headunit/releases/tag/v1.04
