### ISSUE TITLE
MZD Native resolution

### ISSUE THREAD

**Issue by achuman** [gartnera/headunit#84]
I've noticed that it seems like Android Auto doesn't run at the native resolution of the MZD system LCD panel making things like text seem blurred.

I've checked the code and found this in outputs.cpp
_#if ASPECT_RATIO_FIX
**"axis-left=0 axis-top=-20 disp-width=800 disp-height=520"**
#else
"axis-left=0 axis-top=0 disp-width=800 disp-height=480"
#endif
" max-lateness=1000000000 sync=false async=false";_

It seems the native resolution is 800x480.  ASPECT_RATIO_FIX is set to true in another class.  
20 is being deducted off the top, so only 20 needs to be added to fill up the screen right? Seems like 40 is being added in which would cause the app to run 20 pixels too tall.

Anybody know why 40 was added instead of just the 20?

Chris

**Comment by lmagder** [comment]
It's on purpose. unfortunately the CMU uses 800x480 but at a 16:9 aspect ratio with non-square pixels. AA doesn't support this. It only supports 800x480 but with square pixels and optionally adding black bars to the sides of the image. So instead we add black bars to make the image 16:9 then crop them off on the car. This results in a non 1-1 pixel mapping but it's close and the correct aspect ratio. 40 is added since the value is the total height not the size of the bar so it includes the size of both 20 top and bottom bars

Does that make sense or am I missing something about your question?

**Comment by Trevelopment** [comment]
That explained it pretty perfectly my friend

**Comment by achuman** [comment]
No perfectly explained!  Thanks guys!
