### ISSUE TITLE
Versioning Releases

### ISSUE THREAD

**Issue by Trevelopment** [gartnera/headunit#85]
As you may or may not know I am the developer for MZD-AIO.  It easily gets over 20,000 downloads a month and since we fixed the Bluetooth issue I have gotten well over 50 thank you emails and numerous forum post  thank yous so I want to pass that along to you @lmagder & @mishaaq because you guys deserve them too for your hard work and haxor skillz.  Your efforts are not going unnoticed.
Anyways, I have been clearly versioning releases for AA to coincide with AIO releases and I think we should synchronize the version numbers so as not to cause any confusion.  In the current AIO release v2.7.0 I use a headunit binary compiled from the latest commit: https://github.com/gartnera/headunit/commit/9d305e2913b3fc16437fec505db36bd9319ecf 

For this version I used v1.04.  I got to 1.04 because the last official release in this repo was v0.94 (from exactly 1 year ago 9/30/2016) and I have released several versions myself since then up to the latest one.  

I felt through the rules of [Semantic Versioning](http://semver.org/) that the v1.0 line was crossed when headunit was refactored into a long-running service here: https://github.com/gartnera/headunit/commit/d0706eab21dbac9fca2ca3c967ded59e9faf1da6. Since then this is the 4th release I have included in AIO.  

So I will tag this commit v1.04 and we can make a release for it.  If you guys agree with this or just DGAF  then go ahead and close this issue and we can continue versioning from there.

https://github.com/gartnera/headunit/releases/tag/v1.04

Also @lmagder I wanted to make sure AAlogPoll was working for you now because it should be working.

**Comment by lmagder** [comment]
That sounds good to me. I think your reasoning for the versioning is logical so I vote we go with that.

One of the open issues https://github.com/gartnera/headunit/issues/60 is actually to make a release and I haven't. Partially out of having large outstanding bugs, partly out of laziness, and partly since I didn't want to deal with people who bricked their cars because they couldn't read the instructions. Building from source kind of acted as a filter. 😃 

That said, if you want to distribute a last-know-good downstream version via AIO, we could just direct people to that. kind of a Linux Kernel vs. ready to go Ubuntu distro relationship. People who aren't comfortable building from source can use AIO and people who want to hack can build from source here and either use AIO with their binary or the standalone installer.

My only request is that we keep the standalone installer/JA app in this repo working since it's useful as independent test and for people who only want AA and not the rest of AIO.

@Trevelopment Yup, it works for me now thanks.

**Comment by lmagder** [comment]
Also, damn I had no idea how many people are using this. Awesome!

**Comment by Trevelopment** [comment]
@lmagder of coarse, the release I'm suggesting would just be the standalone Mazda installer with compiled binary that would be ready for installation by just unzipping contents to a USB drive. (I think if someone wants the Ubuntu version they can compile it because they already have to have Ubuntu to run it).  I agree completely that some want to be able to just install AA and may not be comfortable compiling from code (or don't have a Linux machine to do it on) that is the main reason I am suggesting this.  Also the good thing is that this last release wont brick anyone's system and putting it up as the latest releases will discourage people from downloading the much older versions that will (if you do a factory reset).  At this point it is very stable, I have not had many reports of crashing or any major issues with this version other than the ones we already know about so it seems like a good point to make the release.  

But what does JA app mean?   That is the one thing I didn't get in your response.

Even if only %5 of those downloads translate into AA users that is still 1,000 people a month and by my accounts it is at least that many and now that we fixed that calling issue the user count will easily double the next month... probably more.

**Comment by lmagder** [comment]
Sorry I meant JS app, it was a typo. 

I thought you were suggesting that we would only offer official binaries via AIO since there is a larger user community there to help with problems, etc. but sure putting an offical binary release and closing https://github.com/gartnera/headunit/issues/60 is also fine with me. My trepidation about putting binary releases here may be baseless since as you said, many people have been using recent builds for a while and it's been fine and the latest one here is likely more risky anyway.

**Comment by Trevelopment** [comment]
Right, cool.  I'm going to go ahead and do that I think you'll see that it's a good idea.

**Comment by mishaaq** [comment]
I think @lmagder is the leader of this project and I'm only a guy who fixed the backup camera issue :), so I think the questions in the first comment should be answered only by him. Anyway, I DGAF when it comes to versioning, but it would be fine for me to leave the standalone installer.

**Comment by Trevelopment** [comment]
Thats cool @mishaaq I was just giving you some props.  I basically just made the release for those who can't compile a headunit binary themselves.  And you still have more to contribute, I've been following the video focus issue progress. So keep up the good work if we can fix this video focus issue it would be awesome since it is the last very big bug left.
